"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Redpanda Data, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _NullValue:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _NullValueEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NullValue.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NULL_VALUE: _NullValue.ValueType  # 0

class NullValue(_NullValue, metaclass=_NullValueEnumTypeWrapper):
    """`NullValue` is a representation of a null value."""

NULL_VALUE: NullValue.ValueType  # 0
global___NullValue = NullValue

@typing.final
class StructValue(google.protobuf.message.Message):
    """`StructValue` represents a struct value which can be used to represent a
    structured data value.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Value: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Value]: ...
    def __init__(
        self,
        *,
        fields: collections.abc.Mapping[builtins.str, global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fields", b"fields"]) -> None: ...

global___StructValue = StructValue

@typing.final
class ListValue(google.protobuf.message.Message):
    """`ListValue` represents a list value which can be used to represent a list of
    values.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___ListValue = ListValue

@typing.final
class Value(google.protobuf.message.Message):
    """`Value` represents a dynamically typed value which can be used to represent
    a value passed to an agent.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NULL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    INTEGER_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    STRUCT_VALUE_FIELD_NUMBER: builtins.int
    LIST_VALUE_FIELD_NUMBER: builtins.int
    null_value: global___NullValue.ValueType
    string_value: builtins.str
    integer_value: builtins.int
    double_value: builtins.float
    bool_value: builtins.bool
    bytes_value: builtins.bytes
    @property
    def timestamp_value(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def struct_value(self) -> global___StructValue: ...
    @property
    def list_value(self) -> global___ListValue: ...
    def __init__(
        self,
        *,
        null_value: global___NullValue.ValueType = ...,
        string_value: builtins.str = ...,
        integer_value: builtins.int = ...,
        double_value: builtins.float = ...,
        bool_value: builtins.bool = ...,
        timestamp_value: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        bytes_value: builtins.bytes = ...,
        struct_value: global___StructValue | None = ...,
        list_value: global___ListValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "integer_value", b"integer_value", "kind", b"kind", "list_value", b"list_value", "null_value", b"null_value", "string_value", b"string_value", "struct_value", b"struct_value", "timestamp_value", b"timestamp_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "integer_value", b"integer_value", "kind", b"kind", "list_value", b"list_value", "null_value", b"null_value", "string_value", b"string_value", "struct_value", b"struct_value", "timestamp_value", b"timestamp_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["kind", b"kind"]) -> typing.Literal["null_value", "string_value", "integer_value", "double_value", "bool_value", "timestamp_value", "bytes_value", "struct_value", "list_value"] | None: ...

global___Value = Value

@typing.final
class Message(google.protobuf.message.Message):
    """Message represents a piece of structured data that flows through the runtime."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERIALIZED_FIELD_NUMBER: builtins.int
    STRUCTURED_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    serialized: builtins.bytes
    @property
    def structured(self) -> global___Value: ...
    @property
    def metadata(self) -> global___StructValue: ...
    def __init__(
        self,
        *,
        serialized: builtins.bytes = ...,
        structured: global___Value | None = ...,
        metadata: global___StructValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata", "payload", b"payload", "serialized", b"serialized", "structured", b"structured"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata", "payload", b"payload", "serialized", b"serialized", "structured", b"structured"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["payload", b"payload"]) -> typing.Literal["serialized", "structured"] | None: ...

global___Message = Message

@typing.final
class TraceContext(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACE_ID_FIELD_NUMBER: builtins.int
    SPAN_ID_FIELD_NUMBER: builtins.int
    TRACE_FLAGS_FIELD_NUMBER: builtins.int
    trace_id: builtins.str
    span_id: builtins.str
    trace_flags: builtins.str
    def __init__(
        self,
        *,
        trace_id: builtins.str = ...,
        span_id: builtins.str = ...,
        trace_flags: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["span_id", b"span_id", "trace_flags", b"trace_flags", "trace_id", b"trace_id"]) -> None: ...

global___TraceContext = TraceContext

@typing.final
class Trace(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SPANS_FIELD_NUMBER: builtins.int
    @property
    def spans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Span]: ...
    def __init__(
        self,
        *,
        spans: collections.abc.Iterable[global___Span] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["spans", b"spans"]) -> None: ...

global___Trace = Trace

@typing.final
class Span(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AttributesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Value: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Value | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    SPAN_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    ATTRIBUTES_FIELD_NUMBER: builtins.int
    CHILD_SPANS_FIELD_NUMBER: builtins.int
    span_id: builtins.str
    name: builtins.str
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def attributes(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Value]: ...
    @property
    def child_spans(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Span]: ...
    def __init__(
        self,
        *,
        span_id: builtins.str = ...,
        name: builtins.str = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        attributes: collections.abc.Mapping[builtins.str, global___Value] | None = ...,
        child_spans: collections.abc.Iterable[global___Span] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["attributes", b"attributes", "child_spans", b"child_spans", "end_time", b"end_time", "name", b"name", "span_id", b"span_id", "start_time", b"start_time"]) -> None: ...

global___Span = Span

@typing.final
class InvokeAgentRequest(google.protobuf.message.Message):
    """InvokeAgentRequest is the request message for the `InvokeAgent` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    TRACE_CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> global___Message: ...
    @property
    def trace_context(self) -> global___TraceContext: ...
    def __init__(
        self,
        *,
        message: global___Message | None = ...,
        trace_context: global___TraceContext | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "trace_context", b"trace_context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "trace_context", b"trace_context"]) -> None: ...

global___InvokeAgentRequest = InvokeAgentRequest

@typing.final
class InvokeAgentResponse(google.protobuf.message.Message):
    """InvokeAgentResponse is the response message for the `InvokeAgent` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    TRACE_FIELD_NUMBER: builtins.int
    @property
    def message(self) -> global___Message: ...
    @property
    def trace(self) -> global___Trace: ...
    def __init__(
        self,
        *,
        message: global___Message | None = ...,
        trace: global___Trace | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["message", b"message", "trace", b"trace"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "trace", b"trace"]) -> None: ...

global___InvokeAgentResponse = InvokeAgentResponse
